service: serverless-crypto-analysis


provider:
  name: aws
  runtime: python3.6
  region: eu-central-1
  stage: ${opt:stage, "dev"}

package:
  excludeDevDependencies: true
  exclude:
    - "*/**"

custom:
  unique_stack_name: ${self:service}
  bucket_glue: ${self:custom.unique_stack_name}-glue
  bucket_data: ${self:custom.unique_stack_name}

  glue_role: arn:aws:iam::077590795309:role/glue-admin

  bucket_glue_url: s3://${self:custom.bucket_glue}
  
  glue_get_coinmarketcap_data: get_coinmarketcap_data
  glue_get_coinmarketcap_data_script: ${self:custom.bucket_glue_url}/get_coinmarketcap_data.py
  
  glue_newcomers: newcomers
  glue_newcomers_script: ${self:custom.bucket_glue_url}/newcomers.py
  glue_get_coinmarketcap_data_libs: ${self:custom.bucket_glue_url}/libs

  s3Sync:
    - bucketName: ${self:custom.bucket_glue}
      localDir:  serverless_crypto_analysis/glue


plugins:
  - serverless-s3-remover
  - serverless-s3-sync

# functions:
#   newcomers:
#     handler: serverless_crypto_analysis/lambda_function/newcomers.handler
#     events:
#       # Invoke Lambda function every minute
#       - schedule: rate(1 hour)
#     envrionment:
#       BUCKET: ${self:custom.bucket_data}
#       KEY: stg/newcomers

resources:
  Resources:
    S3GlueBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket_glue}
    S3DataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket_data}
    GlueJobGetCoinmarketcap:
      Type: AWS::Glue::Job
      Properties: 
        Role: ${self:custom.glue_role}
        Command:   
          Name: pythonshell
          PythonVersion: 3
          ScriptLocation: ${self:custom.glue_get_coinmarketcap_data_script}
        Name: ${self:custom.glue_get_coinmarketcap_data}
        DefaultArguments:
          --extra-py-files: ${self:custom.glue_get_coinmarketcap_data_libs}/pyarrow-0.14.1-cp36-cp36m-manylinux1_x86_64.whl,${self:custom.glue_get_coinmarketcap_data_libs}/requests-2.22.0-py2.py3-none-any.whl,${self:custom.glue_get_coinmarketcap_data_libs}/s3fs-0.3.4-py3-none-any.whl
    GlueSchedulerGetCoinmarketcap:
      Type: AWS::Glue::Trigger
      Properties:
        Type: SCHEDULED
        Schedule: cron(0 * * * ?)        
        Actions:
          - JobName: ${self:custom.glue_get_coinmarketcap_data}
        Name: ${self:custom.glue_get_coinmarketcap_data}
    GlueJobNewcomers:
      Type: AWS::Glue::Job
      Properties: 
        Role: ${self:custom.glue_role}
        Command:   
          Name: pythonshell
          PythonVersion: 3
          ScriptLocation: ${self:custom.glue_newcomers_script}
        Name: ${self:custom.glue_newcomers}
        DefaultArguments:
          --extra-py-files: ${self:custom.glue_get_coinmarketcap_data_libs}/pyarrow-0.14.1-cp36-cp36m-manylinux1_x86_64.whl,${self:custom.glue_get_coinmarketcap_data_libs}/requests-2.22.0-py2.py3-none-any.whl,${self:custom.glue_get_coinmarketcap_data_libs}/s3fs-0.3.4-py3-none-any.whl
 
