service: serverless-crypto-analysis


provider:
  name: aws
  runtime: python3.6
  region: eu-central-1
  stage: ${opt:stage, "dev"}
  role: arn:aws:iam::077590795309:role/serverless-crypto-analysis-prd-eu-central-1-lambdaRole

package:
  excludeDevDependencies: true
#  exclude:
#    - "*/**"
  exclude:
    - 'node_modules/**'
    - 'serverless_crypto_analysis_tests/**'

custom:
  unique_stack_name: ${self:service}-${self:provider.stage}
  bucket_glue: ${self:custom.unique_stack_name}-glue
  bucket_data: ${self:custom.unique_stack_name}
  key_raw_coinmarketcap: raw/coinmarketcap_data
  key_stg_newcomers: stg/newcomers
  glue_role: arn:aws:iam::077590795309:role/glue-admin

  bucket_glue_url: s3://${self:custom.bucket_glue}
  
  glue_get_coinmarketcap_data:  ${self:custom.unique_stack_name}-get_coinmarketcap_data
  glue_get_coinmarketcap_data_script: ${self:custom.bucket_glue_url}/get_coinmarketcap_data.py
  
  glue_newcomers: ${self:custom.unique_stack_name}-newcomers
  glue_newcomers_script: ${self:custom.bucket_glue_url}/newcomers.py
  glue_get_coinmarketcap_data_libs: ${self:custom.bucket_glue_url}/libs

  s3Sync:
    - bucketName: ${self:custom.bucket_glue}
      localDir:  serverless_crypto_analysis/glue


plugins:
  - serverless-s3-remover
  - serverless-s3-sync
  - serverless-python-requirements

functions:
  newcomers:
    handler: serverless_crypto_analysis/lambda_function/newcomers.lambda_handler
    events:
      - s3:
          bucket: ${self:custom.bucket_data}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${self:custom.key_raw_coinmarketcap}
            - suffix: .parquet
    environment:
      ATHENA_DB: coinmarketcap
      ATHENA_TABLE: prd_coinmarketcap_data
      BUCKET_DATA: ${self:custom.bucket_data}
      KEY_DATA: ${self:custom.key_stg_newcomers}
      RANK: "[200,100,75,50,40,30,20,10,5]"
#      RANK: "[200,100,50]"
    timeout: 900
  tweet_newcomers:
    handler: serverless_crypto_analysis/lambda_function/tweets.lambda_handler
    events:
      - s3:
          bucket: ${self:custom.bucket_data}
          event: s3:ObjectCreated:*
          rules:
            - prefix: ${self:custom.key_stg_newcomers}
            - suffix: .json
    environment:
      TWITTER_TOKEN: twitter_token
      COINMARKETCAP_TOKEN: coinmarketcap_token
    timeout: 900
resources:
  Resources:
    S3GlueBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucket_glue}
    GlueJobGetCoinmarketcapData:
      Type: AWS::Glue::Job
      Properties: 
        Role: ${self:custom.glue_role}
        Command:   
          Name: pythonshell
          PythonVersion: 3
          ScriptLocation: ${self:custom.glue_get_coinmarketcap_data_script}
        Name: ${self:custom.glue_get_coinmarketcap_data}
        DefaultArguments:
          --extra-py-files: ${self:custom.glue_get_coinmarketcap_data_libs}/requests-2.22.0-py2.py3-none-any.whl,${self:custom.glue_get_coinmarketcap_data_libs}/awswrangler-0.2.1-glue-none-any.whl
          --bucket: ${self:custom.bucket_data}
          --key: ${self:custom.key_raw_coinmarketcap}
    GlueTriggerGetCoinmarketcapData:
      Type: AWS::Glue::Trigger
      Properties:
        Type: SCHEDULED
        Schedule: cron(0 * * * ?)        
        Actions:
          - JobName: ${self:custom.glue_get_coinmarketcap_data}
            Arguments:
              --bucket: ${self:custom.bucket_data}
              --key: ${self:custom.key_raw_coinmarketcap}
        Name: ${self:custom.glue_get_coinmarketcap_data}
