service: serverless-crypto-analysis


provider:
  name: aws
  runtime: python3.6
  region: eu-central-1

package:
  individually: true
  excludeDevDependencies: false
  exclude:
    - "*/**"

resources:
  Resources:
    GlueJob:
      Type: AWS::Glue::Job
      Properties: 
        Role: ${self:custom.glue_role}
        Command:   
          Name: pythonshell  
          ScriptLocation: ${self:custom.glue_job_script_location}
        Name: ${self:custom.glue_job}
#
#custom:
#  pythonRequirements:
#    dockerizePip: non-linux

# functions:
#   get_coinmarketcap_data:
#     handler: serverless_crypto_analysis/get_coinmarketcap_data.handler
#     layers:
#       - arn:aws:lambda:eu-central-1:077590795309:layer:fastparquet:3
#layers:
#  GetCoinmarketcapData:
#    path: /Users/vincent/.local/share/virtualenvs/serverless_crypto_analysis-yCVEiR5j/lib/python3.6/site-packages/ # required, path to layer contents on disk
#    name: ${self:provider.stage}-${self:service} # optional, Deployed Lambda layer name
#    description: Description of what the lambda layer does # optional, Description to publish to AWS
#    compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
#      - python3.6
#    retain: false # optional, false by default. If true, layer versions are not deleted as new ones are created


